language: node_js

branches:
  only:
    - master

env:
  - TRAVIS_TAG="$(git tag -l --points-at HEAD)"

if: tag IS present

node_js:
    - "8"
    - "9"
    - "10"
    - "11"

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: npm release
      node_js: "11"
      script: echo "Deploying to npm ..."
      script: npm run build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true 
          repo: fvhockney/lautfm-api
    - stage: make docs
      node_js: "11"
      script: echo "Publishing Docs"
      script: npm run docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        target_granch: gh-pages
        local_dir: "./docs"
        on:
          tags: true
          repo: fvhockney/lautfm-api
