language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: npm release
      node_js: '11'
      script: echo "Deploying to npm ..."
      script: npm run build
      deploy:
        provider: npm
        email: fvhockney@gmail.com
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
          repo: fvhockney/lautfm-api
          branch: master
    - stage: make docs
      node_js: '11'
      script: echo "Publishing Docs"
      script: npm run docs
      deploy:
          provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          keep_history: true
          target_branch: gh-pages
          local_dir: "./docs"
          on:
            tags: true
            repo: fvhockney/lautfm-api
            branch: master
